import uniqid from "uniqid";

export const productList = {
  products: [
    {
      id: uniqid(),
      name: "TEK SERPANTİNLİ BOYLER",
      slug: "tek-serpantinli-boyler",
      productCode: "FENNEX Storaqua Single",
      listImage: "https://i.hizliresim.com/k3z3q9f.png",
      image: [
        "https://i.hizliresim.com/8jepwyw.png",
        "https://i.hizliresim.com/mjg3yh4.png",
        "https://i.hizliresim.com/kah1yfp.png",
        "https://i.hizliresim.com/nhrni0a.png",
        "https://i.hizliresim.com/4bmqky7.png",
      ],
      description:
        "Emayeli FENNEX Storaqua Single Tek Serpantinli Boyler, otellerden binalara, villalardan fabrikalara ve sıcak su ihtiyacı olan herhangi bir yerde kullanılarak, tek bir ısı kaynağı aracılığıyla (sıcak su kazanı, buhar kazanı, güneş enerjisi panelleri, ısı pompası, jeotermal enerji vb.) sıcak suyun hızlı bir şekilde hazırlanmasını ve depolanmasını sağlamaktadır",
      technicalSpecificationsList: [
        "Hijyenik ve korozyona (aşınmaya) karşı dayanıklılık için 250-450 mikron titanyum katkılı emaye kullanılmıştır.",
        "100 litreden 1000 litreye kadar ürünlerde, 44 kg/m³ yoğunluğunda ve 50 mm kalınlığında sert poliüretan izolasyon bulunmaktadır.",
        "Katodik koruma için 26*300 mm magnezyum anot çubuk bulunmaktadır.",
        "İsteğe bağlı olarak paslanmaz elektrik rezistans eklenebilir.",
        "Farklı renk seçenekleri ile sade ve şık bir görünüme sahiptir.",
        "10 bar işletme basıncına sahiptir.",
        "İsteğe bağlı serpantin içi de emaye kaplama yapılabilir.",
        "Bilindiği üzere boylerlerde deformasyon ilk serpantin içerisinden başlar. Sadece dıştan kaplı emayelere göre dıştan ve içten emaye kaplama, serpantin içindeki korozyonu ve defermasyonu da önler.",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "C sınıfı enerji grubuna dahildir.",
        "Ürünün 2 yıl garantisi bulunmaktadır",
      ],
    },
    {
      id: uniqid(),
      name: "ÇİFT SERPANTİNLİ BOYLER",
      slug: "cift-serpantinli-boyler",
      productCode: "FENNEX Storaqua Twin",
      listImage: "https://i.hizliresim.com/k3z3q9f.png",
      image: [
        "https://i.hizliresim.com/8jepwyw.png",
        "https://i.hizliresim.com/r84o3fl.png",
        "https://i.hizliresim.com/kah1yfp.png",
        "https://i.hizliresim.com/nhrni0a.png",
        "https://i.hizliresim.com/4bmqky7.png",
      ],
      description:
        "Emayeli FENNEX Storaqua Twin Çift Serpantinli Boyler, otellerden binalara, villalardan fabrikalara ve sıcak su ihtiyacı olan herhangi bir yerde kullanılarak, farklı ısı kaynakları aracılığıyla (sıcak su kazanı, buhar kazanı, güneş enerjisi panelleri, ısı pompası, jeotermal enerji vb.) sıcak suyun hızlı bir şekilde hazırlanmasını ve depolanmasını sağlamaktadır",
      technicalSpecificationsList: [
        "Hijyenik ve korozyona (aşınmaya) karşı dayanıklılık için 250-450 mikron titanyum katkılı emaye kullanılmıştır.",
        "100 litreden 1000 litreye kadar ürünlerde, 44 kg/m³ yoğunluğunda ve 50 mm kalınlığında sert poliüretan izolasyon bulunmaktadır.",
        "Katodik koruma için 26*300 mm magnezyum anot çubuk bulunmaktadır.",
        "İsteğe bağlı olarak paslanmaz elektrik rezistans eklenebilir.",
        "Farklı renk seçenekleri ile sade ve şık bir görünüme sahiptir.",
        "10 bar işletme basıncına sahiptir.",
        "İsteğe bağlı serpantin içi de emaye kaplama yapılabilir.",
        "Bilindiği üzere boylerlerde deformasyon ilk serpantin içerisinden başlar. Sadece dıştan kaplı emayelere göre dıştan ve içten emaye kaplama, serpantin içindeki korozyonu ve defermasyonu da önler.",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "C sınıfı enerji grubuna dahildir.",
        "Ürünün 2 yıl garantisi bulunmaktadır",
      ],
    },
    {
      id: uniqid(),
      name: "ISı POMPASI BOYLER",
      slug: "isi-pompasi-boyler",
      productCode: "FENNEX Storaqua Twin",
      listImage: "https://i.hizliresim.com/k3z3q9f.png",
      image: [
        "https://i.hizliresim.com/8jepwyw.png",
        "https://i.hizliresim.com/r84o3fl.png",
        "https://i.hizliresim.com/kah1yfp.png",
        "https://i.hizliresim.com/nhrni0a.png",
        "https://i.hizliresim.com/4bmqky7.png",
      ],
      description:
        "Emayeli FENNEX Storaqua for Heat Pump ısı pompası boyleri çevrede bulunan doğal enerjiyi kullanarak son derece verimli bir şekilde ısıtma sağlar. Elektrik enerjisinin sadece %25’ini kullanarak, geri kalan %75’ini doğal kaynaklardan elde edilen ısı enerjisine dönüştürür. Bu sayede hem enerji tasarrufu sağlanır hem de çevrenin korunması desteklenir. Bu boylerler, düşük rejimlerde etkili bir şekilde çalışabilen bir seçenektir. Diğer boyler çeşitlerine kıyasla daha geniş bir serpantin yüzey alanına sahip olmaları sebebiyle düşük ısıtıcı akışkan sıcaklıklarında yüksek performans gösterirler. Bu özellikleri, ısıtıcının verimliliğini artırarak sistemlerin daha verimli çalışmasını sağlar. Yüksek teknolojisi sayesinde, FENNEX Storaqua for Heat Pump güvenilir ve sağlam bir ısınma kaynağıdır. Hava kaynaklı ısı pompaları ile ev konforunu en üst düzeye çıkarırken geleceğinizi düşünmekte ve çevreyi korumayı hedeflemektedir. Bu şekilde, doğal kaynakların korunması ve gelecek nesillere temiz bir çevre bırakma amacını sürdürebilirsiniz.",
      technicalSpecificationsList: [
        "Ürün yelpazemiz, 100 litreden başlayıp 300 litreye kadar değişen çeşitli seçenekler sunmaktadır.",
        "Bu boylerler hijyenik ve korozyona karşı dayanıklılık sağlamak için 250-450 mikron titanyum katkılı emaye ile kaplanmıştır.",
        "Magnezyum anot çubuklarla katodik koruma mekanizması bulunmaktadır",
        "Paslanmaz elektrik rezistansları kullanılarak üretilmiştir.",
        "Beyaz renkli ve zarif bir görünüme sahip olan bu boylerler isteğe bağlı olarak farklı renk seçenekleri sunmaktadır.",
        "İşletme basıncı 10 bar ve dizayn basıncı ise 13 bar olarak tasarlanmıştır. Ayrıca, kolay ve hızlı montaj imkanı sağlarlar.",
        "İsteğe bağlı serpantin içi de emaye kaplama yapılabilir.",
        "Bilindiği üzere boylerlerde deformasyon ilk serpantin içerisinden başlar. Sadece dıştan kaplı emayelere göre dıştan ve içten emaye kaplama, serpantin içindeki korozyonu ve defermasyonu da önler.",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "C sınıfı enerji grubuna dahildir.",
        "Ürünün 2 yıl garantisi bulunmaktadır",
      ],
    },
    {
      id: uniqid(),
      name: "AKÜMÜLASYON TANKI",
      slug: "akumulasyon-tanki",
      productCode: "FENNEX Storaqua for Heat Pump",
      listImage: "https://i.hizliresim.com/k3z3q9f.png",
      image: [
        "https://i.hizliresim.com/8jepwyw.png",
        "https://i.hizliresim.com/mjg3yh4.png",
        "https://i.hizliresim.com/kah1yfp.png",
        "https://i.hizliresim.com/nhrni0a.png",
        "https://i.hizliresim.com/4bmqky7.png",
      ],
      description:
        "FENNEX Storaqua Accumulation Akümülasyon tankları, hijyenik depolama gerektiren ısıtma ve soğutma sistemlerinde şartlandırılmış suyun saklanması için kullanılır. Genellikle bir ısı değiştirici (plakalı eşanjör, borulu eşanjör, boyler, chiller, fancoil vb.) ile birlikte kullanılırlar. FENNEX Akümülasyon tankları, villa, otel, bina, restoran, fabrika ve sıcak suya ihtiyaç duyulan her türlü mekanda kullanılabilirler",
      technicalSpecificationsList: [
        "250-450 mikron titanyum katkılı emaye kaplama.",
        "100 litre ile 1000 litre arasında 50 mm kalınlığında 44 kg/m³ sert poliüretan veya 30 mm kalınlığında 18 kg/m³ yumuşak poliüretan izolasyon seçeneği.",
        "800 litre ile 5000 litre arasında ürünlerde 30 mm kalınlığında 15 kg/m³ yumuşak poliüretan izolasyon.",
        "Magnezyum anot çubukla katodik koruma sağlanması.",
        "İsteğe bağlı paslanmaz elektrik rezistans seçeneği.",
        "Gri renkte şık ve minimalist bir tasarım sunması (İsteğe bağlı olarak farklı renk seçenekleri mevcuttur).",
        "10 bar işletme basıncı ve 13 bar tasarım basıncı sağlama kabiliyeti",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "C sınıfı enerji grubuna dahildir.",
        "Ürünün 2 yıl garantisi bulunmaktadır",
      ],
    },
    {
      id: uniqid(),
      name: "Endüstriyel Tip Elektrikli Boyler",
      slug: "endustriyel-tip-elektrikli-boyler",
      productCode: "FENNEX Storawqua Industrial",
      listImage: "https://i.hizliresim.com/6i0oyyv.png",
      image: ["https://i.hizliresim.com/6i0oyyv.png"],
      description:
        "Doğal gaz erişimi mümkün olmadığında veya basit bir kurulum gerektiğinde, Azam TX geniş bir elektrikli su ısıtıcısı yelpazesi sunar. Elektrikli ısıtıcılarımız yüksek güç ve 115 ila 450 litre kapasite sunar ve daha az yer kaplayan sistemlerdir. Bunlar, konut, ticari veya endüstriyel ihtiyaçlar için kullanılabilir.FENNEX Storaqua Industrial elektrikli su ısıtıcısı serisi, ağır sıcak su talepleri olan büyük ölçekli endüstriyel ortamlara (3 faz 400 volt) kadar her boyuttaki gereksinimleri karşılar.FENNEX Storaqua Industrial dayanıklı ve değiştirilebilir ısıtma elemanlarıyla birlikte gelir. Sistemler, bir kontrol termostatı, bir güvenlik termostatı ve bir sıfırlama düğmesi ile kontrol edilir.                  Elektrikli su ısıtıcılarımızkullanımı kolay ve uzunbir servis ömrü içintasarlanmıştır. Son derecekolay kurulabilen bu ısıtıcılarneredeyse her yerdekurulabilir. Bu esneklik sıkçaideal bir seçim yapmalarınısağlar. Tüm Azam TXelektrikli su ısıtıcıları veürettiğimiz diğer ürünlerCE onayına uygundur. 3-9adet maksimum 54.0 kWdeğerinde ısıtma elemanı ilebirlikte gelir.Her bir eleman, 49°C - 82°Carasında ayarlanabilenbir kontrol termostatı vemanuel sıfırlama düğmesiolan bir güvenlik termostatıkullanılarak kontrol edilir.",
      technicalSpecificationsList: [
        "Sürekli ve hızlı ısıtma için elemanların kaskad kontrolü vardır.",
        "Tüm elemanlar ve termostatlar sigorta ile korunmaktadır.",
        "Korozyon, full emaye ile önlenmektedir.",
        "Kuru ateşe karşı koruma ile donatılmıştır",
        "Değiştirilebilir magnezyum anot vardır.",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "C sınıfı enerji grubuna dahildir.",
        "Ürünün 2 yıl garantisi bulunmaktadır",
      ],
    },
    {
      id: uniqid(),
      name: "BUFFERTANK",
      slug: "buffertank",
      productCode: "FENNEX Storaqua Buffertank",
      listImage: "https://i.hizliresim.com/k2pm31a.png",
      image: [
        "https://i.hizliresim.com/k2pm31a.png",
        "https://i.hizliresim.com/1ypb4bl.png",
      ],
      description:
        "FENNEX Storaqua Buffertank, içi su dolu bir haznedir ve yenilenebilir enerji sistemlerinde kullanılarak verimliliği arttırmayı ve birden fazla ısı kaynağını tek bir sistemde birleştirmeyi amaçlar. Isı pompalarının montajında da tavsiye edilen bir bileşendir. Bu tank, ısı pompası tarafından ısıtılan suyu depolar ve gerektiği zaman sisteme sağlayarak enerji depolama işlevi görür. Ayrıca, ısı pompalarının sürekli dur-kalk yapmasını önleyerek ömrünü ve verimini artırır. FENNEX Storaqua Buffertank, esnek kullanım imkanı sağlar ve ısı pompasını farklı ısı kaynaklarıyla desteklemeyi mümkün kılar. Isı pompalarının minimum su debisi gereksinimini karşılamaları için de önemlidir.",
      technicalSpecificationsList: [
        "Düşük maliyetli kurulum imkanı sağlayan bir yapıya sahiptir.",
        "Hem giriş hem de çıkış olarak birden fazla ısı kaynağını bir araya getirme özelliğine sahiptir.",
        "Esneklik sunarak farklı saatlerde suyu ısıtmak içinkullanılabilir.",
        "Korozyonu önlemek ve koruma sağlamak amacıyla çiftkat antipas boya kullanılmıştır.",
        "Yüksek izolasyon sağlamak için 18 kg/m3 yoğunluğunda ve 50 mm kalınlığında soft poliüretankullanılmıştır.",
        "Çalışma basıncı 8 bar olarak belirlenmiştir.",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "C sınıfı enerji grubuna dahildir.",
        "Ürünün 2 yıl garantisi bulunmaktadır",
      ],
    },
    {
      id: uniqid(),
      name: "ELEKTRİKLİ ISITICILI BOYLER",
      slug: "elektirikli-ısıtıcılı-boyler",
      productCode: "FENNEX Storaqua Electric",
      listImage: "https://i.hizliresim.com/4dzuzpb.png",
      image: [
        "https://i.hizliresim.com/4dzuzpb.png",
        "https://i.hizliresim.com/fyidsu2.png",
      ],
      description:
        "FENNEX Storaqua Electric Elektrikli Isıtıcılı Boyler,otellerden binalara, villalardan fabrikalara ve sıcak suihtiyacı olan herhangi bir yerde kullanılarak, herhangi bir ısıkaynanğının bulunmadığı yerlerde (sıcak su kazanı, buharkazanı, güneş enerjisi panelleri, ısı pompası, jeotermalenerji vb.) elektrik enerjisiyle sıcak suyun hızlı bir şekildehazırlanmasını ve depolanmasını sağlamaktadır.",
      technicalSpecificationsList: [
        "Hijyenik ve korozyona (aşınmaya) karşı dayanıklılık için 250-450 mikron titanyum katkılı emaye kullanılmıştır.",
        "100 litre ile 1000 litre arasındaki ürünlerde, 44 kg/m³ yoğunluğunda ve 50 mm kalınlığında sert poliüretan izolasyon bulunmaktadır",
        "Katodik koruma için 26*300 mm magnezyum anot çubuk bulunmaktadır.",
        "İsteğe bağlı olarak paslanmaz elektrik rezistans eklenebilir.",
        "Farklı renk seçenekleri ile sade ve şık bir görünüme sahiptir",
        "10 bar işletme basıncına ve 13 bar dizayn basıncına sahiptir",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "C sınıfı enerji grubuna dahildir.",
        "Ürünün 2 yıl garantisi bulunmaktadır",
      ],
    },
    {
      id: uniqid(),
      name: "ELEKTRİKLİ KOMBİ",
      slug: "elektirikli-kombi",
      productCode: "FENNEX Electric Combi Boiler",
      listImage: "https://i.hizliresim.com/6geohvf.png",
      image: [
        "https://i.hizliresim.com/6geohvf.png",
        "https://i.hizliresim.com/o7299yg.png",
      ],
      description:
        "FENNEX Electric Combi Boiler Kombi 14 kWve 18 kW kapasiteli alternatifler, hem küçükhem de büyük metrekareli kullanım alanlarıiçin en uygun çözümleri sunmaktadır.İstenilen hızda ayarlanabilen pompakademesi sayesinde enerji tasarrufusağlayan yüksek verimli bir pompakullanılmaktadır.Isıtma ünitesi cihazın içine merkezi olarakmonte edilmiş ve ısı izolasyon malzemesiile kaplanmıştır. Isıtma gövdesi çelik sacdanüretilmiştir.",
      technicalSpecificationsList: [
        "%11 modülasyon oranıyla yüksek düzeyde enerji tasarrufu sağlanmaktadır.",
        "Kaskad bağlantı seçeneği sayesinde 7 adede kadar cihaz bir araya getirilebilmektedir.",
        "Ek bir kontrol paneline ihtiyaç duymadan cihaz üzerinden boyler ve ısıtma sistemi kontrol edilebilmektedir.",
        "Elektrikle çalışması sayesinde zararlı gaz salınımı olmamaktadır.",
        "Daha az yer kaplayan kompakt boyutları, esnek montaj imkanı sunmaktadır.",
        "Harici boyler bağlantısı sayesinde her türlü ihtiyaca uygun çözümler sunulmaktadır.",
        "Yaşam alanlarında ses kirliliğini önlemektedir. Geniş LCD ekranı ve kontrol düğmeleri sayesinde kolay kullanım sağlamaktadır.",
        "Baca bağlantısı gerektirmediği için kolaylıkla monte edilebilmektedir.",
        "Mikropların üremesini engellemektedir.",
        "Tesisattaki hava kabarcıklarını engelleyerek uzun ömürlü kullanım sağlamaktadır.",
        "Dahili 3 bar emniyet ventili, cihaz içinde oluşan fazla basıncı dengelemektedir.",
        "Uzun ömürlü kullanım imkanı sunmaktadır ve donmalara karşı koruma sağlamaktadır",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "C sınıfı enerji grubuna dahildir.",
      ],
    },
    {
      id: uniqid(),
      name: "YOĞUŞMALI KOMBİ",
      slug: "yogusmali-kombi",
      productCode: "FENNEX Gas Combi Boiler",
      listImage: "https://i.hizliresim.com/o7299yg.png",
      image: [
        "https://i.hizliresim.com/o7299yg.png",
        "https://i.hizliresim.com/6geohvf.png",
      ],
      description:
        "FENNEX Gas Combi Boiler Yoğuşmalı Kombi 24 kW, 28 kW ve 35 kW seçenekleriyle eviniz için enuygun çözümü sunar. Yüksek verimli A sınıfı ısıtma teknolojisi sayesinde enerji tasarrufu sağlar. Şık bir tasarıma sahiptir. Sadece 1.5 litrede sıcak su sağlamaözelliğiyle hızlı ve sürekli sıcak sutemin eder.",
      technicalSpecificationsList: [
        "Paslanmaz çelik malzemeden üretilmiş eşanjör ile yüksek verimli ısı transferi sağlar.",
        "Geniş LCD ekranı ve kolay kullanımlı çevirmeli kontrol düğmeleriyle kullanıcı dostu bir kontrol paneline sahiptir",
        "XL akış profilinde A sınıfı verimlilik sağlayarak kullanım suyu tasarrufu yapmanızı sağlar.",
        "Ortamın ihtiyaçlarına uygun güçte çalışabilen akıllı bir ısıtma sistemiyle konforlu bir ısınma sağlar.",
        "İhtiyaca göre otomatik olarak ayarlanabilen pompa kademesi sayesinde elektrik tasarrufu sağlar",
        "Sıcaklık ihtiyacına bağlı olarak fan hızını otomatik olarak ayarlayarak enerji verimliliği sağlar.",
        "Yaşam alanlarında sessiz bir kullanım sunar, ses kirliliği yaratmaz.",
        "6. sınıf NOx emisyon seviyesinde düşük emisyon salınımı gerçekleştirir, çevre dostu bir seçenektir.",
        "Ön cepheden müdahale imkanı sayesinde kolay bir şekilde bakım yapılabilir.",
        "Güvenli ve uzun süreli kullanım için üstün güvenlik donanımlarına sahiptir.",
        "Zorlayıcı kullanım şartlarında 15 yıla eşdeğer testlerden geçirilmiş üstün bir kaliteye sahiptir.",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "C sınıfı enerji grubuna dahildir.",
      ],
    },
    {
      id: uniqid(),
      name: "TERMOBOYLER",
      slug: "termoboyler",
      productCode: "FENNEX AquaFervent Plus",
      listImage: "https://i.hizliresim.com/1jv02rw.png",
      image: [
        "https://i.hizliresim.com/sqm3ykm.png",
        "https://i.hizliresim.com/aoxs1v1.png",
        "https://i.hizliresim.com/1jv02rw.png",
        "https://i.hizliresim.com/dyajz1i.png",
      ],
      description:
        "FENNEX AquaFervent Plus Termoboyler, suyu elektrik enerjisiyle birlikte yardımcı bir ısı kaynağı kullanarak ısıtan ve depolayan serpantinli bir termoboylerdir. Bu termoboyler, merkezi sistem kazan, kalorifer, jeotermal ısı ve güneş enerjisi sistemleri gibi çeşitli kaynaklardan gelen sıcak suyu serpantinlerinde dolaştırarak içerisindeki suyu ısıtır.",
      technicalSpecificationsList: [
        "Yüksek enerji tasarrufu sağlar.",
        "İstenilen su sıcaklığı dijital kumanda paneli ile ayarlanabilir.",
        "Özel serpantin dizaynı sayesinde yüksek sıcak su verimine sahiptir.",
        "Poliüretan izolasyonuyla yüksek seviyede ısı yalıtımı sağlar.",
        "Güvenli kullanım için ilave emniyet termostatı bulunmaktadır.",
        "İç yüzey, elektrostatik emaye ile korozyona karşı korunmuş ve uzun ömürlüdür.",
        "Ani basınç yükselmelerine karşı emniyet ventili mevcuttur.",
        "Maksimum işletme basıncı: 10 bardır.",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "Ürün, 2 yıl garantili olup satış sonrası hizmet imkanı sunmaktadır.",
      ],
    },
    {
      id: uniqid(),
      name: "TERMOSİFON",
      slug: "termosifon",
      productCode: "FENNEX AquaFervent",
      listImage: "https://i.hizliresim.com/84njx1n.png",
      image: [
        "https://i.hizliresim.com/84njx1n.png",
        "https://i.hizliresim.com/5tk2u0l.png",
        "https://i.hizliresim.com/pghfpbf.png",
        "https://i.hizliresim.com/4c23f98.png",
      ],
      description:
        "FENNEX AquaFervent Termosifon günlük yaşamımızın vazgeçilmez bir parçası olan sıcak su ihtiyacını karşılamak için kullanabileceğiniz kaliteli ve konforlu bir sıcak su çözümü sunar. İleri teknoloji ve sağlam tasarımlarıyla termosifonlarımız, kullanıcılara yüksek performans ve uzun ömürlü bir kullanım deneyimi sağlar. FENNEX AquaFervent’in özel emaye teknolojisi sayesinde uzun ömürlü olması da önemli bir faktördür. Bu teknoloji, iç haznenin dayanıklılığını artırır ve korozyona karşı etkili bir koruma sağlar. Böylece, termosifonun kullanım ömrü uzar ve sorunsuz bir performans sunar.",
      technicalSpecificationsList: [
        "İki kat daha hızlı ısıtma teknolojisi sayesinde zamandan tasarruf sağlanır.",
        "Programlama özelliği düşük elektrik sarfiyatıyla enerji tasarrufu sağlar.",
        "Özel emaye teknolojisi, ürünün uzun ömürlü olmasını sağlar.",
        "4 farklı emniyet sistemi, güvenli bir tasarım sunar.",
        "Korozyona karşı koruma önlemi alınmıştır.",
        "Anti-lejyoner fonksiyonu hijyenik su konforunu sağlar.",
        "Yüksek kaliteli izolasyon, enerji tasarrufu sağlar.",
        "Avrupa standartlarına uygun şekilde tasarlanmıştır.",
        "Ürün, 2 yıl garantili olup satış sonrası hizmet imkanı sunmaktadır.",
      ],
    },
  ],
};
